name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi9:latest
      volumes:
        - volume:/volume_mount
    steps:
      - name: Install Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
          nvm install 22
          node -v
          npm -v
