name: CI
on:
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi8:latest
      volumes:
        - /artifacts_storage:/artifacts_storage
    steps:
      - name: Install Tools
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_22.x -o- | bash
          yum install -y nodejs xz
          node -v
      - name: Install Firefox dependencies
        run: |
          yum install -y gtk3 # libgtk-3.so.0
          yum install -y libasound2 # libasound.so.2
      - name: Install and run puppeteer
        run: |
          mkdir project
          cd project
          npm init -y
          npm install puppeteer
          npx puppeteer browsers install firefox
          ls
          node -e "require('puppeteer').launch({ browser: 'firefox' }).then(browser => browser.newPage().then(page => page.goto('https://example.com').then(() => browser.close())))"
        env:
          HOME: /root
      - name: Extract libgtk-3.so.0 files
        run: |
          # ldd /lib64/libgtk-3.so.0
          cp /lib64/libgtk-3.so.0 /artifacts_storage
          ldd /lib64/libgdk-3.so.0 | grep -P -o '(?<==> )\S*' | xargs -I '{}' cp '{}' /artifacts_storage
          ls /artifacts_storage
      - name: Extract libtracker-sparql-3.0.so.0 files
        run: |
          ldd /lib64/libtracker-sparql-3.0.so.0
          cp /lib64/libtracker-sparql-3.0.so.0 /artifacts_storage
          ldd /lib64/libtracker-sparql-3.0.so.0 | grep -P -o '(?<==> )\S*' | xargs -I '{}' cp '{}' /artifacts_storage
          ls /artifacts_storage
      - name: Upload lib files
        uses: actions/upload-artifact@v4
        with:
          path: /artifacts_storage/**