name: CI
on:
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi9:latest
      volumes:
        - /artifacs_storage:/artifacs_storage
    steps:
      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_22.x -o- | bash
          yum install -y nodejs xz
          node -v
      - name: Install Firefox dependencies
        run: |
          yum install -y gtk3 # libgtk-3.so.0
      - name: Install and run puppeteer
        run: |
          mkdir project
          cd project
          npm init -y
          npm install puppeteer
          npx puppeteer browsers install firefox
          ls
          node -e "require('puppeteer').launch({ browser: 'firefox' }).then(browser => browser.newPage().then(page => page.goto('https://example.com').then(() => browser.close())))"
      - name: Extract lib files
        run: |
          ldconfig -p | grep libgtk-3.so.0