name: CI
on:
  push:
    branches: [ main ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: redhat/ubi9:latest
      volumes:
        - volume:/volume_mount
    steps:
      - name: Install Node.js
        run: |
          curl -fsSL https://rpm.nodesource.com/setup_22.x -o- | bash
          yum install -y nodejs
          node -v
      - name: Install puppeteer test
        run: |
          npm init -y
          npm install puppeteer
          npx puppeteer install firefox
          ls
          node -e "require('puppeteer').launch().then(browser => browser.newPage().then(page => page.goto('https://example.com').then(() => browser.close())))"
